apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: prelude   ##
  labels:
    role: api
    env: dev          ##
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
      #
      annotations:                                                              ##  for vault
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-status: 'update'
        vault.hashicorp.com/role: 'internal-app'
        vault.hashicorp.com/agent-inject-secret-database-config.txt: 'internal/data/database/config'
        #vault.hashicorp.com/agent-inject-secret-root-password: 'secret/data/mongodb_root_password'
      #
    spec:
      #imagePullSecrets:
      #- name: ecr-registry-secret      ### pending **
      serviceAccount: mern-app-sa                                                ##  for vault
      containers:
      - name: api
        image: 137068254036.dkr.ecr.ap-south-1.amazonaws.com/backend-repo:10
        imagePullPolicy: Always
        env:
          - name: MONGO_CONN_STR
            value: mongodb://mongodb-svc:27017/todo?directConnection=true

          # - name: MONGO_USERNAME
          #   valueFrom:
          #     secretKeyRef:
          #       name: mongo-sec
          #       key: username

        ports:
        - containerPort: 3500
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3500
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3500
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /started
            port: 3500
          initialDelaySeconds: 0
          periodSeconds: 10
          failureThreshold: 30
